# Prometheus configuration file
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Scrape web servers (if they expose metrics)
  - job_name: 'web-servers'
    static_configs:
      - targets: ['web1:5000', 'web2:5000', 'web3:5000']